version: '3.9'
services:
  db:
    build:
      context: .
    container_name: rss_db_container
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - rss_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app
    container_name: rss_app_container
    restart: unless-stopped
    env_file: .env  
    environment:
      RSS_FEED_URL: ${RSS_FEED_URL}       
      POLL_INTERVAL: ${POLL_INTERVAL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
    command: ["python", "main.py"]


volumes:
  rss_data:
